### ISSUE TITLE
Do you accept submissions?

### ISSUE THREAD

**Issue by Wilfred** [wasamasa/microblog#2]
I was amused today that test/manual/etags/Makefile contains the following:

```
REGEX=/[ \t]*DEFVAR_[A-Z_ \t\n(]+"\([^"]+\)"/
xx="this line is here because of a fontlock bug
```

Emacs source itself has workarounds for highlighting bugs of its own code, rather than, you know, fixing it :)

**Comment by wasamasa** [comment]
Yes, I do!  While I haven't tested it yet, there is support in the Atom feed for other authors than just me.  I'm not sure how to highlight it in the posts though, but I'm sure I'll figure it out once you submit a PR with your guest post.

**Comment by Wilfred** [comment]
As discussed on IRC, I'd love to contribute, but I've decided against it. I want to be positive to help make things better.
